{
 "title": "MaomiMQ",
 "description": "https://github.com/whuanle/Maomi.MQ",
 "tags": [
  "RabbitMQ",
  "Maomi",
  "AMQP"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "AppName", "query": { "query": "label_values(AppName)" } },
   { "name": "Queue", "query": { "query": "label_values(Queue)" } },
   { "name": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Publish message",
   "type": "timeseries",
   "description": "Number of published messages",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(maomimq_publisher_message_count_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Publish message faild",
   "type": "timeseries",
   "description": "Number of failed messages to publish",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(maomimq_publisher_message_faild_count_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pull message",
   "type": "timeseries",
   "description": "The speed at which messages are pulled\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(maomimq_consumer_message_pull_count_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Faild Message",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(maomimq_consumer_message_faild_count_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received message size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(maomimq_consumer_message_received_Byte_sum[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Publish",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "maomimq_publisher_message_count_total-maomimq_publisher_message_faild_count_total",
     "legendFormat": "publush success"
    },
    {
     "expr": "maomimq_publisher_message_faild_count_total",
     "legendFormat": "publish faild"
    }
   ]
  }
 ]
}