{
 "title": "MaomiMQ",
 "description": "https://github.com/whuanle/Maomi.MQ",
 "tags": [
  "RabbitMQ",
  "Maomi",
  "AMQP"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "AppName", "query": { "query": "label_values(AppName)" } },
   { "name": "Queue", "query": { "query": "label_values(Queue)" } },
   { "name": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Publish message count",
   "type": "timeseries",
   "description": "Number of published messages",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(maomimq_publisher_message_count_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer pull message count",
   "type": "timeseries",
   "description": "The speed at which messages are pulled\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(maomimq_consumer_message_pull_count_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Publish message faild count",
   "type": "timeseries",
   "description": "Number of failed messages to publish",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(maomimq_publisher_message_faild_count_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer message faild count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(maomimq_consumer_message_faild_count_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer received message size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(maomimq_consumer_message_received_Byte_sum[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Publish message count(top10)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "topk(10,maomimq_publisher_message_count_total)",
     "legendFormat": "{{AppName}}-{{Queue}}"
    }
   ]
  },
  {
   "title": "Pull message count(top10)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,maomimq_consumer_message_pull_count_total)",
     "legendFormat": "{{AppName}}-{{Queue}}"
    }
   ]
  }
 ]
}