<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="RabbitMQ.Client" />
		<PackageReference Include="Microsoft.Extensions.Hosting" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Maomi.MQ.Core\Maomi.MQ.Core.csproj" />
	</ItemGroup>

</Project>
