<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
	</PropertyGroup>

	<ItemGroup>
		<None Include="package.png" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MessagePack" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Maomi.MQ.Core\Maomi.MQ.Core.csproj" />
	</ItemGroup>

</Project>
