<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
	</PropertyGroup>

	<ItemGroup>
		<None Include="package.png" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MediatR" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Maomi.MQ.RabbitMQ\Maomi.MQ.RabbitMQ.csproj" />
	</ItemGroup>

</Project>

